### ISSUE TITLE
传参里有 \" 会报错

### ISSUE THREAD

**Issue by ccforeverd** [xiachufang/actions-feishu#9]
``` yml
with:
    webhook: ***
    message_type: template
    msg_template_path: .github/scripts/feishu/card.json
    msg_template_values: {"message":"fix: test message \"test\"","content":"**modified:**\\n  .github/scripts/feishu/card.js\\n\\n"}
    title: Actions Feishu
```
报错 `invalid character 't' after object key:value pair`

经排查是 `"message":"fix: test message \"test\"",` 这里报错, 请大佬帮忙看一下, 感谢
